name: Upload CLI binaries

on:
  release:
    types:
      - created

env:
  TAG: ${{ github.event.release.tag_name }} # had some issue using this directly on windows

jobs:
  server:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib # required to build for 32-bit arch
      - name: Cargo build
        working-directory: tmc-langs-cli
        run: |
          cargo build --release --verbose --features server
      - name: Deploy
        run: gsutil cp target/${{ matrix.target }}/release/tmc-langs-cli gs://${{ secrets.GCP_BUCKET }}/tmc-langs-rust/tmc-langs-cli-server-$TAG

  linux:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        target: [i686-unknown-linux-gnu, x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib # required to build for 32-bit arch
      - name: Cargo build
        working-directory: tmc-langs-cli
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --verbose --target ${{ matrix.target }}
      - name: Deploy
        run: gsutil cp target/${{ matrix.target }}/release/tmc-langs-cli gs://${{ secrets.GCP_BUCKET }}/tmc-langs-rust/tmc-langs-cli-${{ matrix.target }}-$TAG

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [i686-pc-windows-msvc, x86_64-pc-windows-msvc]
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Cargo build # crt-static is set with RUSTFLAGS to statically link MSVCRT (VCRUNTIME140.dll)
        working-directory: tmc-langs-cli
        run: |
          rustup target add ${{ matrix.target }}
          $env:RUSTFLAGS="-C target-feature=+crt-static"
          cargo build --release --verbose --target ${{ matrix.target }}
      - name: Deploy
        run: |
          $env:python_version=$(python -c 'import sys; print(\".\".join(map(str, sys.version_info[:3])))')
          $env:CLOUDSDK_PYTHON="C:\hostedtoolcache\windows\Python\$env:python_version\x64\python"
          gsutil cp target/${{ matrix.target }}/release/tmc-langs-cli.exe gs://${{ secrets.GCP_BUCKET }}/tmc-langs-rust/tmc-langs-cli-${{ matrix.target }}-$Env:TAG.exe

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Cargo build
        working-directory: tmc-langs-cli
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --verbose --target ${{ matrix.target }}
      - name: Sign
        run: codesign --force -s - target/release/tmc-langs-cli
      - name: Deploy
        run: gsutil cp target/release/tmc-langs-cli gs://${{ secrets.GCP_BUCKET }}/tmc-langs-rust/tmc-langs-cli-${{ matrix.target }}-$TAG

  arm:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        target: [aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf]
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Cargo build
        working-directory: tmc-langs-cli
        run: |
          rustup target add ${{ matrix.target }}
          cargo install cross
          cross build --release --verbose --target ${{ matrix.target }}
      - name: Deploy
        run: gsutil cp target/${{ matrix.target }}/release/tmc-langs-cli gs://${{ secrets.GCP_BUCKET }}/tmc-langs-rust/tmc-langs-cli-${{ matrix.target }}-$TAG
